const { chromium } = require('playwright');
const CHROME = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
let bad = 0;
const ok = (l, c, extra='') => { if (!c) bad++; console.log(`${c ? 'ok  ' : 'FAIL'}  ${l}${extra?'  '+extra:''}`); };

(async () => {
  const b = await chromium.launch({ executablePath: CHROME });
  const p = await b.newPage({ viewport: { width: 390, height: 844 } }); // a phone
  const errs = [];
  p.on('pageerror', e => errs.push(e.message));
  await p.goto('http://localhost:8899/index.html');
  await p.waitForTimeout(600);

  // a real payee address, generated by the reference SDK
  const payee = require('@stellar/stellar-sdk').Keypair.random().publicKey();

  ok('starts with no key and no pay form', await p.isVisible('#mkdev') && !(await p.isVisible('#payform')));

  await p.click('#mkdev');
  await p.waitForTimeout(400);
  ok('creating a key reveals the pay form', await p.isVisible('#payform'));

  await p.fill('#payee', payee);
  await p.fill('#amount', '2.5');
  await p.click('#signbtn');
  await p.waitForTimeout(500);
  const code = await p.inputValue('#code');
  ok('signing produces a 246-character voucher', code.length === 246, `got ${code.length}`);
  const summary = await p.textContent('#paysummary');
  ok('the summary shows the right amount', summary.includes('2.5 XLM'), summary.trim());

  // the payee accepts it
  await p.click('nav button[data-v=recv]');
  await p.fill('#inp', code);
  await p.click('#check');
  await p.waitForTimeout(500);
  let res = await p.textContent('#result');
  ok('a good voucher verifies offline', res.includes('signature checks out'));
  ok('and shows the amount', res.includes('2.5 XLM'));

  await p.click('#result button');
  await p.waitForTimeout(400);
  ok('accepting moves it to the wallet', (await p.textContent('#pending')).includes('2.5 XLM'));

  // tampering must be caught
  await p.click('nav button[data-v=recv]');
  const tampered = code.slice(0, 100) + (code[100] === 'A' ? 'B' : 'A') + code.slice(101);
  await p.fill('#inp', tampered);
  await p.click('#check');
  await p.waitForTimeout(500);
  res = await p.textContent('#result');
  ok('a tampered voucher is refused', res.includes('altered'), res.trim().slice(0, 60));

  // rubbish input must not explode
  await p.fill('#inp', 'hello');
  await p.click('#check');
  await p.waitForTimeout(300);
  ok('rubbish input gives a message, not a crash', (await p.textContent('#result')).includes('voucher code'));

  // a mistyped address must be caught before signing
  await p.click('nav button[data-v=pay]');
  await p.fill('#payee', 'G' + 'A'.repeat(55));
  await p.fill('#amount', '1');
  await p.click('#signbtn');
  await p.waitForTimeout(400);
  ok('a mistyped address is caught', (await p.textContent('#paysummary')).includes('typo'));

  // the key survives a reload, like a real wallet
  await p.reload();
  await p.waitForTimeout(700);
  ok('the device key survives a reload', await p.isVisible('#payform'));

  // offline is the whole point
  await p.context().setOffline(true);
  await p.reload();
  await p.waitForTimeout(900);
  ok('the app still loads with the network off', await p.isVisible('#payform'));
  await p.fill('#payee', payee);
  await p.fill('#amount', '0.75');
  await p.click('#signbtn');
  await p.waitForTimeout(500);
  ok('and can still sign offline', (await p.inputValue('#code')).length === 246);
  await p.context().setOffline(false);

  ok('no uncaught page errors', errs.length === 0, errs.join(' | '));
  await p.screenshot({ path: 'app-shot.png' });
  await b.close();
  console.log(bad ? `\n${bad} FAILURES` : '\nTHE APP WORKS, INCLUDING OFFLINE');
  process.exit(bad ? 1 : 0);
})();
